export const MAX_PAGE = 5;

export const SET_PAGE = "SET_PAGE";
export const SET_USER = "SET_USER";
export const SET_NOTIFICATION_DATA = "SET_NOTIFICATION_DATA";
export const SET_NOTIFICATION_EXTRA = "SET_NOTIFICATION_EXTRA";
export const SET_NOTIFICATION_VALIDATION = "SET_NOTIFICATION_VALIDATION";

export const SET_OTHER_THING = "SET_OTHER_THING";
