export const MAX_PAGE = 5;
export const MAX_LENGTH_SHORT_DESC = 150;
export const MIN_LENGTH_LONG_DESC = 120;
export const MAX_LENGTH_LONG_DESC = 4000;

export const SET_PAGE = "SET_PAGE";
export const SET_USER = "SET_USER";

export const SET_NOTIFICATION_INPUT_LANGUAGE = "SET_NOTIFICATION_INPUT_LANGUAGE";
export const SET_NOTIFICATION_NAME = "SET_NOTIFICATION_NAME";
export const SET_NOTIFICATION_SHORT_DESCRIPTION = "SET_NOTIFICATION_SHORT_DESCRIPTION";
export const SET_NOTIFICATION_LONG_DESCRIPTION = "SET_NOTIFICATION_LONG_DESCRIPTION";
export const SET_NOTIFICATION_TAG = "SET_NOTIFICATION_TAG";
export const SET_NOTIFICATION_NOTIFIER = "SET_NOTIFICATION_NOTIFIER";
export const SET_NOTIFICATION_ADDRESS = "SET_NOTIFICATION_ADDRESS";
export const SET_NOTIFICATION_CONTACT = "SET_NOTIFICATION_CONTACT";
export const SET_NOTIFICATION_LINK = "SET_NOTIFICATION_LINK";
export const SET_NOTIFICATION_PHOTO = "SET_NOTIFICATION_PHOTO";
export const REMOVE_NOTIFICATION_PHOTO = "REMOVE_NOTIFICATION_PHOTO";
export const SET_NOTIFICATION_PRICE = "SET_NOTIFICATION_PRICE";
export const SET_NOTIFICATION_PAYMENT = "SET_NOTIFICATION_PAYMENT";
export const SET_NOTIFICATION_COMMENTS = "SET_NOTIFICATION_COMMENTS";

export const SET_NOTIFICATION_NAME_VALIDATION = "SET_NOTIFICATION_NAME_VALIDATION";
export const SET_NOTIFICATION_SHORT_DESCRIPTION_VALIDATION = "SET_NOTIFICATION_SHORT_DESCRIPTION_VALIDATION";
export const SET_NOTIFICATION_LONG_DESCRIPTION_VALIDATION = "SET_NOTIFICATION_LONG_DESCRIPTION_VALIDATION";
export const SET_NOTIFICATION_TAG_VALIDATION = "SET_NOTIFICATION_TAG_VALIDATION";
export const SET_NOTIFICATION_NOTIFIER_VALIDATION = "SET_NOTIFICATION_NOTIFIER_VALIDATION";
export const SET_NOTIFICATION_ADDRESS_VALIDATION = "SET_NOTIFICATION_ADDRESS_VALIDATION";

export const SET_OTHER_THING = "SET_OTHER_THING";
