/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * <description>
 */
export interface NotificationSchema {
  name: string;
  postal_address: string;
  street_address: string;
  [k: string]: unknown;
}
