/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * <description>
 */
export interface TranslationSchema {
  language: string;
  name: {
    lang: string;
    [k: string]: unknown;
  };
  description: {
    short: {
      lang: string;
      [k: string]: unknown;
    };
    long: {
      lang: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  website: {
    lang: string;
    [k: string]: unknown;
  };
  images: {
    index: number;
    uuid: string;
    source: string;
    alt_text: {
      lang: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
